basePath: /
host: localhost:3000
info:
  contact: {}
  description: This is the API documentation for chamasoft API Fiber app
  version: "1.0"
paths:
  /login:
    post:
      description: '{email,password} input required fields to login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: return
      tags:
      - Login
swagger: "2.0"
